### ISSUE TITLE
Disable console logging in release build

### ISSUE THREAD

**Issue by icl7126** [LiCybora/NanoDefenderFirefox#101]
Hello,

Could you please remove console statements (including warnings) from the build file that is being deployed?
I'm pretty sure I've seen it in some policy rules not to spam console with logs. 
Imagine if every add-on would be printing there something... 

Thank you! 
And congratulation for the AMO release! I've been waiting for this a long time.

**Comment by LiCybora** [comment]
I guess it is likely to be declined according to the upstream homepage...

...
<p><strong>Can console messages be turned off?</strong></p>
        <p>No, I need to see the console output on your end to quickly find the cause of your issues, that is why I ask for a screenshot of the console when you open an issue.</p>
        <p>In production mode, all the console messages will begin with <code>[Nano]</code>, so you can easily filter them out.</p>

...

I remember all warnings are removed in release build already. For a site normally operate, it should only log whether the site is activated, and with some errors (in red) indicating which rules trigger (or failed when abnormal). These are often just a line or two indicate status and as said above, can be filtered out easily.

However, if you think ND log too much, you may provide the sample site with console screenshot so I can know which message should be reduced. I will also review the policy to see how it should be improve.

**Comment by icl7126** [comment]
There are other ways to achieve your goal without using the console. 
For example:
1) make logging optional in options page - replace all console.log statements with custom "log" function that will have a simple if statement that will check this value
1) you could collect all errors in one buffer in the background script (your custom "log" function could use "browser.runtime.sendMessage({type: 'log', severity: 1, message: 'xxx'})" for that) and then have one button that will print it all - or you can even prefill e-mail body using "mailto" protocol.
1) log everything in the background script - again by using "browser.runtime.sendMessage" method. That way all your logs will be on the same place.

Please think about other developers, and imagine that you have go through someones logs just to see yours.

Regarding affected pages - this happens on many pages, I just opened console on a google search result page and see this:
```
[Nano] Nano Defender Activated :: www.google.com core.js:12:5
[Nano] Excluded :: All Generically Applied Solutions rules-common.js:177:9
[Nano] Nano Defender Activated :: notifications.google.com core.js:12:5
[Nano] Excluded :: All Generically Applied Solutions
```

**Comment by LiCybora** [comment]
> Please think about other developers, and imagine that you have go through someones logs just to see yours

I guess most developers will use filter to see their own output, as the error/warnings from many websites are much more than just 2 or several lines. 

I do rethink your point not to fill up console, but I do not want to deviate from upstream too much. I guess upstream will decline it just as the homepage written. IMO, these logs are neat, clear and harmless, and should not be banned from policy. But in case the console log is really unwanted, might be adding a master toggle switch in popup, or move the console log to somewhere as you said for the Mozilla version in future.

One more thing, seems you are somehow familiar with coding, if you have good idea you may submit a pull request, this may increase the chance you persuade the upstream. I might also consider it in Mozilla version if it is good.

**Comment by icl7126** [comment]
Are you using filters to see only your errors? :)
Because I don't - my add-ons are composed out of multiple files and many errors in promises are even missing file name so I'm sure I don't want to filter those out.

The extensive logging of many web-pages is indeed irritating, but it is not an excuse to do it as well. 
I have 18 add-ons installed and if every one of them would print just 2 lines into console, it would be crazy (all you need is one crazy add-on that would print mousemove event or any other event). 

I'm writing you this because none of the other 17 add-ons prints anything there. Production code should not have info logs, unless some kind of debugging switch is on.

Regarding help - I'm sorry but I'm too busy with my own projects, I'm happy to help you on the "architectural level" but the implementation itself it always faster done by the author.

**Comment by LiCybora** [comment]
I guess the reason for printing console is that some codes is causing anti-adblock malfunction, but this might break also normal site (or maybe fails due to racing condition). From console log with browser error logs I can know which rules break which things or which rules malfunctioning quickly, so no not just only my errors.

I do see your point that filtering can be troublesome in that case. Moreover, little users reports site issue here and (maybe just directly to quick issue reporter?) and thus the usage is somehow limited. I might consider adding a master switch to toggle off the logging when not required in later version.

@jspenguin2017 Any thought for this issue? As an official port I think it is better not to diverge too much.

**Comment by jspenguin2017** [comment]
> I'm pretty sure I've seen it in some policy rules not to spam console with logs.

Link? I have never seen anything like that. 

> make logging optional in options page

Not possible on Chromium, loses race condition. It is possible on Firefox, if @LiCybora wants to invest time to implement. 

If you think you can implement it, you can help @LiCybora out by creating a PR. 

> you could collect all errors in one buffer in the background script

This can be difficult to implement as not all code have access to the `chrome` / `browser` namespace. Some code are injected to the page scope. 

If you think you can implement it, a PR is welcomed upstream. I think this is easier to implement than an option to turn off logs, not to mention that it is going to be more useful as well because most people use Quick Issue Reporter now. 

> Please think about other developers

Many `net::ERR_BLOCKED_BY_CLIENT` will be logged when using an adblocker anyway, I recommend you to develop with another browser profile. 

You can filter out all logs from Nano Adblocker and Nano Defender with `-[Nano]` or something equivalent for Firefox. 
![image](https://user-images.githubusercontent.com/7283682/52607110-4f963f80-2e32-11e9-8b84-1608e43d71a4.png)

> I'm too busy with my own projects

Well, same here. 

My projects are personal projects, and I don't get anything from implementing a feature that I don't need. You are free to use something else, or to contribute

**Comment by jspenguin2017** [comment]
> I'm pretty sure I've seen it in some policy rules not to spam console with logs.

Link? I have never seen anything like that. 

> make logging optional in options page

Not possible on Chromium, loses race condition. It is possible on Firefox, if @LiCybora wants to invest time to implement. 

If you think you can implement it, you can help @LiCybora out by creating a PR. 

> you could collect all errors in one buffer in the background script

This can be difficult to implement as not all code have access to the `chrome` / `browser` namespace. Some code are injected to the page scope. 

If you think you can implement it, a PR is welcomed upstream. I think this is easier to implement than an option to turn off logs, not to mention that it is going to be more useful as well because most people use Quick Issue Reporter now. 

> Please think about other developers

Many `net::ERR_BLOCKED_BY_CLIENT` (or something equivalent for Firefox?) will be logged when using an adblocker anyway, I recommend you to develop with another browser profile. 

You can filter out all logs from Nano Adblocker and Nano Defender with `-[Nano]` (or something equivalent for Firefox). 
![image](https://user-images.githubusercontent.com/7283682/52607110-4f963f80-2e32-11e9-8b84-1608e43d71a4.png)

> I'm too busy with my own projects

Well, same here. 

My projects are personal projects, and I do not get anything from implementing a feature that I do not need. You are welcomed to contribute back to a project that you are using for free, or you can use something else. If you want to wait for me to implement it, open an issue upstream and wait patiently.

**Comment by jspenguin2017** [comment]
> As an official port I think it is better not to diverge too much.

It already diverged enough, so as long as it does not cause me headaches, it's fine. Just keep in mind that I still want to see those logs when people open issues in my repository.

**Comment by LiCybora** [comment]
![image](https://user-images.githubusercontent.com/40160522/52613763-3b9e1c80-2eca-11e9-8565-035aba6ef5c0.png)
Unfortunately, the minus filter seems really not work on Firefox. Then it may be mandatory to work with this issue. This will need some time, so maybe wait for several version.

**Comment by icl7126** [comment]
@jspenguin2017 
Let's try this simple and bulletproof solution:
```javascript
let log = (...params) => console.log(...params);
browser.storage.local.get('debuggingOn').then(({debuggingOn}) => {if (!debuggingOn) log = () => {} })
```
Just two lines and it disables logging when some property is set. As far as I know, `browser.storage` (and also `browser.runtime.sendMessage`) is available in all contexts, including content scripts so this should work without any issues or race conditions.

And btw, I'm also add-on developer with 0 income, so I think I'm contributing enough. And if you are not willing to help a fellow programmers, then I can just wish you that all your favorite add-ons starts logging to your console so that you can have a same conversation with some other busy developer.

**Comment by jspenguin2017** [comment]
> Let's try this simple and bulletproof solution

Most logs are written synchronously, by the time the promise is resolved, it's too late. Also, page scope (sometimes called main world) does not have access to `chrome.runtime` / `browser.runtime`. 

If it's so easy two lines of code, why don't you create a PR? 

> I can just wish you that all your favorite add-ons starts logging to your console

When that happens, I will contribute back instead of whining in the issues tracker. 

If you think you contributed enough, that's fine, but that's not a reason for me to contribute more.

**Comment by LiCybora** [comment]
> However, Firefox has some extra APIs that can be used to modify content scripts at runtime.

Not exactly modified, but allow you load/unload content script files/scripts at runtime. Even so, it is still useful, and is what I use to deal with this issue.

I patched most, if not all console messages (those log from web resources are not tested due to dead link/strict block by default uBO filter). You may enable/disable console log from the popup. Notice that I still not ask for storage permission at this moment, so whenever you restart your browser session, it will enable again. If it looks good, I will release it today or tomorrow. You may try the [pre-release](https://github.com/LiCybora/NanoDefenderFirefox/releases/tag/v15.0.0.93b) first (Note: this is unsigned).

**Comment by icl7126** [comment]
Thank you for your help!
It's strange though you don't have a storage permission. This is one of those permission that is not even listed when you install add-on - only if you have ask for "unlimitedStorage".
And storage is must have if you ever want to have any user settings at all. Else usage of "window.localStorage" is not recommended for add-ons and IndexedDB is not very usable for this (and has too many issues in Firefox).

**Comment by gwarser** [comment]
>usage of "window.localStorage" is not recommended for add-ons and IndexedDB is not very usable for this

Should be better in beta - storage backend is [moved to indexedDB](https://bugzilla.mozilla.org/show_bug.cgi?id=1474562) and [indexedDB is hardened](https://bugzilla.mozilla.org/show_bug.cgi?id=1423917)

**Comment by icl7126** [comment]
Yes I remember... and if you downgrade from Beta then all your addons data will be gone :D
https://www.ghacks.net/2018/08/06/dont-downgrade-firefox-63/

Anyway as someone who is using IndexedDB for 2 years I would tell you to stay away from it if you can. Most of the error e-mails I'm getting are related to some crazy IndexedDB bugs in Firefox (I have like 5 e-mail templates related to different DB bugs). But implementation in Chrome is quite solid.

But once they fix this one, it should be much better: 
https://bugzilla.mozilla.org/show_bug.cgi?id=944918
and maybe this one:
https://bugzilla.mozilla.org/show_bug.cgi?id=1478602

**Comment by gwarser** [comment]
>But implementation in Chrome is quite solid.

It's so stable that it was worth mentioning in wikipedia ;)

https://en.wikipedia.org/wiki/LevelDB#Bugs_and_reliability

I wonder how it is still more stable than Firefox.

**Comment by LiCybora** [comment]
v15.0.0.93 is released. Note that only the version on AMO allow disable console. This rule will also applied for any new features diverged from upstream. The GitHub hosted version will still strictly follow upstream as backup.

**Comment by jspenguin2017** [comment]
@LiCybora 

https://github.com/LiCybora/NanoDefenderFirefox/commit/d86e42422f8864ef2c1063452f4bad96b3f17f98#diff-5d60c7aaac3278606410f6ccdde2fb2c
This is not writing to the console, it is patching the console to detect Instart Logic. The file is not used by Firefox though, so it's up to you. 

https://github.com/LiCybora/NanoDefenderFirefox/commit/d86e42422f8864ef2c1063452f4bad96b3f17f98#diff-82aafd37b19a52bd5b64ea594151fc5d
This will leak a signature to the webpage, you should delete it when all content scripts finished running. For logs written asynchronously in the page scope, Nano Defender will keep a local reference to the log function to prevent webpages from messing with it.

**Comment by LiCybora** [comment]
> This will leak a signature to the webpage, you should delete it when all content scripts finished running.

Opp..this is bad. I forgot the detection problem. I wonder even if I delete it, will some webpage define that namespace to detect whether it is deleted to know if ND is activated.

Another bulletproof solution is to generate another whole set of content scripts come with no console.log at all during build and install, and then swap between two sets during runtime, but it is somehow trivial and resulting unnecessary file size.

> This is not writing to the console, it is patching the console to detect Instart Logic.

Yes this is not in used, though I can revert it.

**Comment by jspenguin2017** [comment]
> will some webpage define that namespace to detect whether it is deleted to know if ND is activated

No, all content scripts run before the first script in the webpage, so as long as you clean up after yourself it's fine.

**Comment by jspenguin2017** [comment]
Yep, that looks good 👍

**Comment by ghajini** [comment]
Hello😃@LiCybora I turned off allow console button in recent release. ......closed firefox and restarted Firefox , allow console is on automatically although I remember I have turned off previously

**Comment by LiCybora** [comment]
> Notice that I still not ask for storage permission at this moment, so whenever you restart your browser session, it will enable again.

Saving setting is not implemented yet. Maybe expect for future version.

**Comment by m0ngr31** [comment]
It'd be great to have this implemented.
